# Generated by Django 5.2.1 on 2025-06-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME', '0002_education_personalinfo_projects_skills_delete_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Projecttitle',
            new_name='Project',
        ),
    ]
