# Generated by Django 5.2.1 on 2025-06-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESUME', '0003_rename_projecttitle_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('institute', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('Project', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
